"use strict";

const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];

const copybook = {
  zh: {
    eyebrow: "给流浪的小爪一点声音", brandZh: "小爪帮帮", brandEn: "PawHelp", tagline: "把遇见写清楚，让帮助更容易发生",
    stepOne: "01 · 填写救助卡", formTitle: "告诉我们你看见了什么", fillExample: "填入示例",
    animalInfo: "动物信息", animalInfoHint: "先写你能确定的，不确定的可以留空。", animalType: "动物", age: "年龄阶段",
    helpNeeded: "需要什么帮助", helpNeededHint: "选择现在最重要的一件事。", condition: "目前情况", helpType: "主要需求",
    whereContact: "地点与联系", whereContactHint: "公开内容中尽量不要写过细的私人地址。", location: "发现地点", contact: "联系方式",
    locationPlaceholder: "如：阳光花园北门", contactPlaceholder: "如：私信我 / 电话",
    voicePlatform: "语气与平台", voicePlatformHint: "文案会随平台稍微调整节奏。", tone: "语气", platform: "发布平台", length: "文字长度",
    details: "补充观察", detailsPlaceholder: "如：左后腿不敢着地，躲在灌木旁，可以靠近", generate: "生成求助文案与卡片",
    privacy: "内容只保存在你的浏览器里，不上传服务器", stepTwo: "02 · 可直接转发", generatedPost: "生成的求助文案", history: "历史记录",
    copyText: "复制文案", share: "分享", edit: "继续编辑", stepThree: "03 · 图片卡片工作室", studioTitle: "做一张真正能转发的求助卡",
    studioHint: "换模板不会清空内容，下载始终可用", shareCard: "分享图片", downloadPng: "保存高清图片", qualityNote: "离线可用 · 高清导出 · 无水印遮挡",
    templates: "选择模板", photoTools: "动物照片", photoHint: "带照片的模板可上传自己的图片，也可直接使用自带图", uploadPhoto: "上传自己的照片", useBuiltIn: "使用自带图", builtInActive: "正在使用自带图", photoReady: "已使用你的照片", cardTipTitle: "小提醒", cardTip: "卡片负责让人停下来，完整情况放在配套文案里更好读",
    installTitle: "把小爪帮帮带在手机里", installText: "添加到手机桌面，遇到流浪猫狗时可以快速打开", installHow: "如何添加到桌面",
    footer: "愿每一次被看见，都离帮助更近一点", footerPrivacy: "内容只保存在你的浏览器", footerObserve: "请以现场观察为准", footerCare: "受伤动物请尽快联系专业救助或宠物医院", disclaimer: "请以现场观察为准；受伤动物应尽快联系专业救助或宠物医院",
    installDialogTitle: "添加小爪帮帮 PawHelp 到主屏幕", gotIt: "知道了", historyTitle: "最近生成", clearHistory: "清空本机记录",
    installIos: "iPhone：用 Safari 打开，点击分享按钮，再选择“添加到主屏幕”",
    installAndroid: "Android：请先用 Chrome 打开本页面",
    installAndroidOpen: "如果正在微信里浏览，请点右上角菜单，选择“在浏览器打开”",
    installAndroidMenu: "在 Chrome 里点右上角 ⋮，选择“安装应用”或“添加到主屏幕”",
    installAndroidReady: "安装完成后，桌面会显示“小爪帮帮 PawHelp”图标",
    saveDialogTitle: "保存求助图片", saveDialogHint: "安卓手机可先打开系统保存/分享；如仍失败，请打开原图后长按保存", systemShare: "打开系统保存 / 分享", openOriginal: "打开原图保存", openedOriginal: "原图已打开，请长按图片保存", androidSaveHint: "已打开安卓保存方式", close: "关闭",
    copyrightButton: "版权与使用说明", copyrightTitle: "版权与使用说明", copyrightLine: "© 2026 小爪帮帮 PawHelp · 保留所有权利",
    copyrightIntro: "小爪帮帮 PawHelp 的程序代码、品牌名称、图标、界面设计、模板和内置视觉素材受版权保护",
    copyrightCode: "未经书面许可，不得复制、出售、重新发布或用于制作同类商业产品",
    copyrightUser: "用户上传的文字和照片仍归原权利人所有；请确认自己有权使用相关内容，并注意隐藏私人信息",
    copyrightRescue: "使用本工具生成的卡片可用于非商业动物救助和公益转发，但不得单独出售模板或内置素材",
    copyrightContact: "本说明用于明确使用边界，不替代正式法律意见",
    copied: "文案已复制", generated: "已生成新的求助文案与卡片", saved: "图片已准备好保存", shareUnavailable: "当前浏览器不支持直接分享，已打开保存图片",
    historyEmpty: "还没有历史记录。生成后的文案会保存在这台设备上。", historyRestored: "已恢复这条记录", cleared: "本机记录已清空",
    cardShared: "图片分享面板已打开", postShared: "分享面板已打开", copyFailed: "复制失败，请长按文案复制", needLocation: "请至少填写一个大概地点",
    unknownLocation: "附近", privateMessage: "请私信联系", observed: "现场观察", helpLabel: "需要", locationLabel: "地点", contactLabel: "联系", footerMark: "小爪帮帮 PawHelp"
  },
  en: {
    eyebrow: "Give a little paw a voice", brandZh: "PawHelp", brandEn: "Writer", tagline: "Tell the story clearly. Make help easier to find.",
    stepOne: "01 · Rescue card", formTitle: "Tell us what you observed", fillExample: "Use an example",
    animalInfo: "Animal info", animalInfoHint: "Only add what you know. Unknown is okay.", animalType: "Animal", age: "Age group",
    helpNeeded: "Help needed", helpNeededHint: "Choose the most important need right now.", condition: "Current condition", helpType: "Primary need",
    whereContact: "Location & contact", whereContactHint: "Avoid posting an overly precise private address.", location: "Location", contact: "Contact",
    locationPlaceholder: "e.g. North gate, Sunny Garden", contactPlaceholder: "e.g. DM me / phone",
    voicePlatform: "Tone & platform", voicePlatformHint: "The rhythm adapts slightly to the platform.", tone: "Tone", platform: "Platform", length: "Text length",
    details: "What you observed", detailsPlaceholder: "e.g. avoids putting weight on the back leg and stays near the bushes", generate: "Generate rescue post & card",
    privacy: "Your content stays in this browser and is never uploaded", stepTwo: "02 · Ready to share", generatedPost: "Generated rescue post", history: "History",
    copyText: "Copy text", share: "Share", edit: "Keep editing", stepThree: "03 · Image card studio", studioTitle: "Make a rescue card people can share",
    studioHint: "Switching templates keeps your content. Download is always ready", shareCard: "Share image", downloadPng: "Save HD image", qualityNote: "Works offline · High resolution · Clean export",
    templates: "Choose a template", photoTools: "Animal photo", photoHint: "Photo templates can use your own upload or the built-in image", uploadPhoto: "Upload your photo", useBuiltIn: "Use built-in photo", builtInActive: "Using built-in photo", photoReady: "Using your photo", cardTipTitle: "Quick tip", cardTip: "Let the card stop the scroll; keep the full story in the accompanying post",
    installTitle: "Keep PawHelp on your phone", installText: "Add it to your home screen for quick access when you meet a stray", installHow: "How to install",
    footer: "May every small life that is seen move one step closer to help", footerPrivacy: "Content stays in your browser", footerObserve: "Share only what you observed", footerCare: "Contact a rescue or vet quickly for injured animals", disclaimer: "Share observed facts only; contact a rescue or veterinary professional for injured animals",
    installDialogTitle: "Add 小爪帮帮 PawHelp to your home screen", gotIt: "Got it", historyTitle: "Recent posts", clearHistory: "Clear local history",
    installIos: "iPhone: Open in Safari, tap Share, then choose Add to Home Screen",
    installAndroid: "Android: First open this page in Chrome",
    installAndroidOpen: "If you are inside WeChat, use the top-right menu and choose Open in browser",
    installAndroidMenu: "In Chrome, tap ⋮ and choose Install app or Add to Home screen",
    installAndroidReady: "After installation, the 小爪帮帮 PawHelp icon will appear on your home screen",
    saveDialogTitle: "Save rescue image", saveDialogHint: "On Android, try the system save/share button first; if it fails, open the original image and press and hold to save", systemShare: "Open system save / share", openOriginal: "Open original image", openedOriginal: "Original image opened; press and hold it to save", androidSaveHint: "Android save options opened", close: "Close",
    copyrightButton: "Copyright & use", copyrightTitle: "Copyright and use notice", copyrightLine: "© 2026 小爪帮帮 PawHelp · All rights reserved",
    copyrightIntro: "The PawHelp source code, brand name, icon, interface, templates, and built-in visual assets are protected by copyright",
    copyrightCode: "No copying, resale, republication, or use in a competing commercial product without written permission",
    copyrightUser: "Users retain rights to their own text and photos; only upload content you may legally use and avoid exposing private information",
    copyrightRescue: "Cards generated here may be used for non-commercial animal rescue and public-interest sharing, but templates and built-in assets may not be sold separately",
    copyrightContact: "This notice explains usage boundaries and is not a substitute for formal legal advice",
    copied: "Post copied", generated: "A new rescue post and card are ready", saved: "Your image is ready to save", shareUnavailable: "Direct sharing is unavailable, so the save preview was opened",
    historyEmpty: "No history yet. Generated posts are stored on this device.", historyRestored: "Post restored", cleared: "Local history cleared",
    cardShared: "Image share sheet opened", postShared: "Share sheet opened", copyFailed: "Could not copy. Please select the post manually.", needLocation: "Please add at least a general location",
    unknownLocation: "this area", privateMessage: "please send a private message", observed: "Observed", helpLabel: "Need", locationLabel: "Location", contactLabel: "Contact", footerMark: "PawHelp Writer"
  }
};

